# Generated by Django 5.2.3 on 2025-07-02 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lab", "0048_participation_on_premises"),
        ("radiation_protection", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskPreventionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date this entry was first created",
                        verbose_name="Created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date this entry was most recently changed.",
                        verbose_name="Modified",
                    ),
                ),
                (
                    "risk_advisor_notification_sent",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the risk advisor has been notified about this plan.",
                        verbose_name="Risk Advisor Notification Sent",
                    ),
                ),
                (
                    "participation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_prevention_plans",
                        to="lab.participation",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_prevention_plans",
                        to="lab.run",
                    ),
                ),
            ],
            options={
                "verbose_name": "Run Risk Prevention Plan",
                "verbose_name_plural": "Run Risk Prevention Plans",
                "unique_together": {("participation", "run")},
            },
        ),
    ]
