# Generated by Django 5.2.5 on 2025-11-03 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radiation_protection", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElectricalSignatureProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider_name",
                    models.CharField(
                        help_text="The name of the electrical signature service provider.",
                        max_length=100,
                        verbose_name="Provider Name",
                    ),
                ),
                (
                    "provider_workflow_id",
                    models.CharField(
                        help_text="The ID of the provider workflow associated with this process.",
                        max_length=255,
                        verbose_name="Provider Workflow ID",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the electrical signature process has been completed.",
                        verbose_name="Is Completed",
                    ),
                ),
                (
                    "risk_prevention_plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="electrical_signature_process",
                        to="radiation_protection.riskpreventionplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Electrical Signature Process",
                "verbose_name_plural": "Electrical Signature Processes",
            },
        ),
    ]
