# Generated by Django 5.2.5 on 2025-11-13 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radiation_protection", "0003_electricalsignatureprocess"),
    ]

    operations = [
        migrations.AddField(
            model_name="electricalsignatureprocess",
            name="label",
            field=models.CharField(
                default="Electrical Signature Process",
                help_text="A descriptive label for the electrical signature process.",
                max_length=255,
                verbose_name="Label",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="electricalsignatureprocess",
            name="risk_prevention_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="electrical_signature_processes",
                to="radiation_protection.riskpreventionplan",
            ),
        ),
    ]
