# Generated by Django 5.2.9 on 2026-01-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radiation_protection", "0004_electricalsignatureprocess_label_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="riskpreventionplan",
            name="electrical_signature_exempt",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if this plan is exempt from electrical signature workflows.",
                verbose_name="Electrical Signature Exempt",
            ),
        ),
    ]
