# Generated by Django 6.0.2 on 2026-03-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radiation_protection", "0005_riskpreventionplan_electrical_signature_exempt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riskpreventionplan",
            name="risk_advisor_notification_sent",
            field=models.BooleanField(
                default=False, verbose_name="Prevention plan sent"
            ),
        ),
    ]
