# Generated by Django 4.0a1 on 2021-09-27 15:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('euphro_auth', '0002_load_group_fixture'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4)),
                ('completed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date this entry was first created', verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date this entry was most recently changed.', verbose_name='Modified')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='euphro_auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('profession', models.CharField(blank=True, max_length=150, null=True, verbose_name='profession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='euphro_auth.user')),
            ],
        ),
    ]
