# Generated by Django 4.0a1 on 2021-09-27 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinvitation',
            name='token',
        ),
    ]
