[tool.black]
extend_exclude = "/migrations/"

[tool.isort]
profile = "black"
multi_line_output = 3
extend_skip_glob = "*migrations*"

[tool.mypy]
ignore_missing_imports = true
files = "lab/methods/"
exclude = '\/migrations\/.*$'
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "euphrosyne.settings"