# Generated by Django 5.2.9 on 2026-01-22 17:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lab", "0053_alter_participation_on_premises"),
    ]

    operations = [
        migrations.CreateModel(
            name="RunData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lifecycle_state",
                    models.CharField(
                        choices=[
                            ("HOT", "Hot"),
                            ("COOLING", "Cooling"),
                            ("COOL", "Cool"),
                            ("RESTORING", "Restoring"),
                            ("ERROR", "Error"),
                        ],
                        default="HOT",
                        max_length=32,
                    ),
                ),
                ("cooling_eligible_at", models.DateTimeField(blank=True, null=True)),
                (
                    "run_size_bytes",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("file_count", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_run_data",
                        to="lab.run",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LifecycleOperation",
            fields=[
                (
                    "operation_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("COOL", "Cool"), ("RESTORE", "Restore")],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("bytes_total", models.PositiveBigIntegerField(blank=True, null=True)),
                ("files_total", models.PositiveBigIntegerField(blank=True, null=True)),
                ("bytes_copied", models.PositiveBigIntegerField(blank=True, null=True)),
                ("files_copied", models.PositiveBigIntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("error_details", models.TextField(blank=True, null=True)),
                (
                    "project_run_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lifecycle_operations",
                        to="data_management.rundata",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="rundata",
            index=models.Index(
                fields=["lifecycle_state"], name="data_manage_lifecyc_0990ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rundata",
            index=models.Index(
                fields=["cooling_eligible_at"], name="data_manage_cooling_dc9c07_idx"
            ),
        ),
    ]
