# Generated by Django 5.2.9 on 2026-01-29 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0001_initial'),
        ('lab', '0053_alter_participation_on_premises'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lifecycleoperation',
            name='project_run_data',
        ),
        migrations.AddField(
            model_name='lifecycleoperation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_operations', to='lab.project'),
        ),
        migrations.CreateModel(
            name='ProjectData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifecycle_state', models.CharField(choices=[('HOT', 'Hot'), ('COOLING', 'Cooling'), ('COOL', 'Cool'), ('RESTORING', 'Restoring'), ('ERROR', 'Error')], default='HOT', max_length=32)),
                ('cooling_eligible_at', models.DateTimeField(blank=True, null=True)),
                ('project_size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('file_count', models.PositiveBigIntegerField(blank=True, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_data', to='lab.project')),
            ],
        ),
        migrations.DeleteModel(
            name='RunData',
        ),
        migrations.AddIndex(
            model_name='projectdata',
            index=models.Index(fields=['lifecycle_state'], name='data_manage_lifecyc_b11d60_idx'),
        ),
        migrations.AddIndex(
            model_name='projectdata',
            index=models.Index(fields=['cooling_eligible_at'], name='data_manage_cooling_eecf2e_idx'),
        ),
    ]
