# Generated by Django 5.2.9 on 2026-02-13 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_management", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectdata",
            name="file_count",
        ),
        migrations.RemoveField(
            model_name="projectdata",
            name="project_size_bytes",
        ),
    ]
