# Generated by Django 6.0.2 on 2026-03-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0002_remove_projectdata_file_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdata',
            name='cooling_eligible_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
