# Generated by Django 6.0.2 on 2026-03-12 17:25

from datetime import datetime, timedelta

from django.db import migrations
from django.db.models import Max
from django.utils import timezone

COOLING_DELAY_DAYS = 30 * 24


def _cooling_delay():
    return timedelta(days=COOLING_DELAY_DAYS)


def _datetime_to_date(value):
    if timezone.is_naive(value):
        return value.date()
    return timezone.localdate(value)


def _compute_cooling_eligible_at(project, Run):
    run_dates = Run.objects.filter(project_id=project.id).aggregate(
        latest_embargo_date=Max("embargo_date"),
        latest_end_date=Max("end_date"),
    )
    latest_embargo_date = run_dates["latest_embargo_date"]
    if latest_embargo_date is not None:
        return latest_embargo_date

    latest_end_date = run_dates["latest_end_date"]
    if latest_end_date is not None:
        if isinstance(latest_end_date, str):
            latest_end_date = datetime.fromisoformat(latest_end_date)
        return _datetime_to_date(latest_end_date + _cooling_delay())

    created_at = project.created
    if isinstance(created_at, str):
        created_at = datetime.fromisoformat(created_at)
    return _datetime_to_date(created_at + _cooling_delay())


def backfill_project_data(apps, schema_editor):
    Project = apps.get_model("lab", "Project")
    Run = apps.get_model("lab", "Run")
    ProjectData = apps.get_model("data_management", "ProjectData")

    for project in Project.objects.all().only("id", "created"):
        ProjectData.objects.get_or_create(
            project_id=project.id,
            defaults={
                "cooling_eligible_at": _compute_cooling_eligible_at(project, Run),
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("data_management", "0003_alter_projectdata_cooling_eligible_at"),
    ]

    operations = [
        migrations.RunPython(
            backfill_project_data,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
