beamlines:
  Microbeam:
    name: External Microbeam
    methods:
      PIXE:
        detectors:
          LEO:
            filters:
              - Helium
              - Air
          HE1:
            filters: &HE-filters
              - "100 µm Be"
              - "100 µm Mylar"
              - "200 µm Mylar"
              - "50 µm Al"
              - "100 µm Al"
              - "150 µm Al"
              - "200 µm Al"
              - "13 µm Cr + 50 µm Al"
              - "50 µm Cu"
              - "75 µm Cu"
              - _
          HE2:
            filters: *HE-filters
          HE3:
            filters: *HE-filters
          HE4:
            filters: *HE-filters
      PIGE:
        detectors:
          HPGe-20:
          HPGe-70:
          HPGe-70-N:
      IBIL:
        detectors:
          QE65000:
      FORS:
        detectors:
          QE65000:
      RBS:
        detectors:
          "PIPS - 130°":
          "PIPS - 150°":
      ERDA:
      NRA:
      _other:
