# Generated by Django 5.1.1 on 2024-10-30 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "type_of",
                    models.CharField(
                        choices=[("QUIZ", "Quiz")],
                        default="QUIZ",
                        max_length=100,
                        verbose_name="Type of certification",
                    ),
                ),
                (
                    "num_days_valid",
                    models.IntegerField(
                        help_text="Number of days the certification is valid", null=True
                    ),
                ),
                (
                    "invitation_to_complete_email_template_path",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Invitation to complete email template path",
                    ),
                ),
                (
                    "success_email_template_path",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Success email template path",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Certification",
                "verbose_name_plural": "Certifications",
            },
        ),
        migrations.CreateModel(
            name="QuizCertification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="https://tally.so/r/3jyvJ6", verbose_name="Quiz URL"
                    ),
                ),
                ("passing_score", models.FloatField(verbose_name="Passing score")),
                (
                    "certification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="certification.certification",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz certification",
                "verbose_name_plural": "Quiz certifications",
            },
        ),
        migrations.CreateModel(
            name="QuizResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField(verbose_name="Score")),
                ("is_passed", models.BooleanField(verbose_name="Quiz passed")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="certification.quizcertification",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz result",
                "verbose_name_plural": "Quiz results",
            },
        ),
        migrations.CreateModel(
            name="CertificationNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_of",
                    models.CharField(
                        choices=[
                            ("INVITATION_TO_COMPLETE", "Invitation to complete"),
                            ("SUCCESS", "Success"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_sent", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "certification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="certification.certification",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "quiz_result",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="certification.quizresult",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certification notification",
                "verbose_name_plural": "Certification notifications",
            },
        ),
    ]
