# Generated by Django 5.0.4 on 2024-05-07 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "num_days_valid",
                    models.IntegerField(
                        help_text="Number of days the certification is valid", null=True
                    ),
                ),
                (
                    "invitation_to_complete_email_template_path",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Invitation to complete email template path",
                    ),
                ),
                (
                    "success_email_template_path",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Success email template path",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="QuizzCertification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="https://tally.so/r/3jyvJ6", verbose_name="Quizz URL"
                    ),
                ),
                ("passing_score", models.FloatField(verbose_name="Passing score")),
                (
                    "certification",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizz",
                        to="certification.certification",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuizzResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField(verbose_name="Score")),
                ("is_passed", models.BooleanField(verbose_name="Quizz passed")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "quizz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="certification.quizzcertification",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CertificationNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_of",
                    models.CharField(
                        choices=[
                            ("INVITATION_TO_COMPLETE", "Invitation to complete"),
                            ("SUCCESS", "Success"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_sent", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "certification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="certification.certification",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "quizz_result_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="certification.quizzresult",
                    ),
                ),
            ],
        ),
    ]
