# Generated by Django 5.1.3 on 2025-01-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certification", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificationnotification",
            name="type_of",
            field=models.CharField(
                choices=[
                    ("INVITATION_TO_COMPLETE", "Invitation to complete"),
                    ("RETRY", "Retry"),
                    ("SUCCESS", "Success"),
                ],
                max_length=50,
            ),
        ),
    ]
