# Generated by Django 5.0.4 on 2024-05-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certification", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="certification",
            name="type_of",
            field=models.CharField(
                choices=[
                    (
                        "<class 'certification.certifications.models.QuizzCertification'>",
                        "Quizz",
                    )
                ],
                default="<class 'certification.certifications.models.QuizzCertification'>",
                max_length=100,
                verbose_name="Type of certification",
            ),
        ),
    ]
