# Generated by Django 5.2.5 on 2025-09-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("to", models.EmailField(max_length=254, verbose_name="Recipient")),
                ("subject", models.CharField(max_length=255, verbose_name="Subject")),
                (
                    "status",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Status"
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="Date")),
            ],
            options={
                "verbose_name": "Email log",
                "verbose_name_plural": "Email logs",
                "managed": False,
            },
        ),
    ]
