# Generated by Django 6.0.4 on 2026-06-16 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0054_normalize_employer_names"),
        ("standard", "0002_alter_measuringpointstandard_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measuringpointstandard",
            name="measuring_point",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="standard",
                to="lab.measuringpoint",
            ),
        ),
    ]
