# Generated by Django 4.0a1 on 2021-10-12 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('euphro_auth', '0005_delete_extra_groups'),
        ('lab', '0002_participation_project_run_delete_experiment_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('user', 'project')},
        ),
    ]
