# Generated by Django 4.0a1 on 2021-10-26 15:38

import django.contrib.postgres.constraints
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


def fill_is_leader_in_participation(apps, _):
    participation_model = apps.get_model("lab", "Participation")
    participation_model.objects.filter(user_id=models.F("project__leader_id")).update(
        is_leader=True
    )


def reverse_fill_is_leader_in_participation(apps, _):
    participation_model = apps.get_model("lab", "Participation")
    participations = participation_model.objects.filter(is_leader=True)
    for participation in participations:
        participation.project.leader_id = participation.user_id
        participation.save()


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0003_alter_participation_unique_together"),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.AddField(
            model_name="participation",
            name="is_leader",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name="participation",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="participation",
            constraint=models.UniqueConstraint(
                fields=("user", "project"), name="unique_user_participation_per_project"
            ),
        ),
        migrations.AddConstraint(
            model_name="participation",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("is_leader", True)),
                expressions=[("project", "=")],
                name="exclude_multiple_leader_participation_per_project",
            ),
        ),
        migrations.RunPython(
            fill_is_leader_in_participation, reverse_fill_is_leader_in_participation
        ),
        migrations.RemoveField(
            model_name="project",
            name="leader",
        ),
    ]
