# Generated by Django 4.0a1 on 2021-11-03 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euphro_auth', '0008_remove_user_invitation_completed_and_more'),
        ('lab', '0005_institution_participation_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_as_admin', to='euphro_auth.user', verbose_name='Administrator'),
        ),
        migrations.AddField(
            model_name='project',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='project',
            name='run_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of run'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(1, 'To schedule')], default=1),
        ),
        migrations.CreateModel(
            name='BeamTimeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date this entry was first created', verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date this entry was most recently changed.', verbose_name='Modified')),
                ('request_type', models.CharField(choices=[('French', 'French'), ('European', 'European'), ('C2RMF', 'C2Rmf'), ('AGLAE', 'Aglae')], max_length=45, verbose_name='Request type')),
                ('request_id', models.CharField(blank=True, help_text='ID appearing on the official form', max_length=45, verbose_name='Request ID')),
                ('problem_statement', models.CharField(blank=True, help_text='Description of the problematic being studied with the beam analysis', max_length=350, verbose_name='Problem statement')),
                ('form_type', models.CharField(blank=True, choices=[('Sciencescall', 'Sciencescall'), ('Hyperion', 'Hyperion'), ('OSCAR', 'Oscar')], max_length=45, verbose_name='Form type')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lab.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
