# Generated by Django 4.0a1 on 2021-11-14 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0007_remove_project_run_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisTechniqueUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('PIXE', 'PIXE'), ('PIGE', 'PIGE'), ('IBIL', 'IBIL'), ('FORS', 'FORS'), ('RBS', 'RBS'), ('ERDA', 'ERDA'), ('NRA', 'NRA'), ('_other', '_other')], max_length=45, verbose_name='Label')),
            ],
        ),
        migrations.RemoveField(
            model_name='run',
            name='date',
        ),
        migrations.AddField(
            model_name='run',
            name='beamline',
            field=models.CharField(blank=True, choices=[('Microbeam', 'External Microbeam')], max_length=45, verbose_name='Beamline'),
        ),
        migrations.AddField(
            model_name='run',
            name='embargo_date',
            field=models.DateField(null=True, verbose_name='Embargo date'),
        ),
        migrations.AddField(
            model_name='run',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='Run end of period'),
        ),
        migrations.AddField(
            model_name='run',
            name='energy_in_keV',
            field=models.IntegerField(null=True, verbose_name='Energy level (in keV)'),
        ),
        migrations.AddField(
            model_name='run',
            name='particle_type',
            field=models.CharField(blank=True, choices=[('Proton', 'Proton'), ('Alpha particle', 'Alpha particle'), ('Deuton', 'Deuton')], max_length=45, verbose_name='Particle type'),
        ),
        migrations.AddField(
            model_name='run',
            name='start_date',
            field=models.DateTimeField(null=True, verbose_name='Run start of period'),
        ),
        migrations.AddField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('Not started', 'Not started'), ('Started', 'Started'), ('Finished', 'Finished')], default='Not started', max_length=45, verbose_name='Run status'),
        ),
        migrations.CreateModel(
            name='DetectorUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=45, verbose_name='Label')),
                ('detector_filter', models.CharField(blank=True, max_length=45, verbose_name='Filter')),
                ('analysis_technique_used', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detectors_used', to='lab.analysistechniqueused')),
            ],
        ),
        migrations.AddField(
            model_name='analysistechniqueused',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_techniques_used', to='lab.run'),
        ),
    ]
