# data= Generated by Django 4.0a1 on 2021-11-22 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0007_remove_project_run_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="run",
            name="date",
        ),
        migrations.AddField(
            model_name="run",
            name="beamline",
            field=models.CharField(
                blank=True,
                choices=[("Microbeam", "External Microbeam")],
                max_length=45,
                verbose_name="Beamline",
            ),
        ),
        migrations.AddField(
            model_name="run",
            name="embargo_date",
            field=models.DateField(blank=True, null=True, verbose_name="Embargo date"),
        ),
        migrations.AddField(
            model_name="run",
            name="end_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Run end of period"
            ),
        ),
        migrations.AddField(
            model_name="run",
            name="energy_in_keV",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Energy level (in keV)"
            ),
        ),
        migrations.AddField(
            model_name="run",
            name="methods",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="run",
            name="particle_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Proton", "Proton"),
                    ("Alpha particle", "Alpha particle"),
                    ("Deuton", "Deuton"),
                ],
                max_length=45,
                verbose_name="Particle type",
            ),
        ),
        migrations.AddField(
            model_name="run",
            name="start_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Run start of period"
            ),
        ),
        migrations.AddField(
            model_name="run",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("Ask for execution", "Ask for execution"),
                    ("Planned", "Planned"),
                    ("Started", "Started"),
                    ("Finished", "Finished"),
                ],
                default="New",
                max_length=45,
                verbose_name="Run status",
            ),
        ),
        migrations.AlterField(
            model_name="run",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="runs",
                to="lab.project",
            ),
        ),
    ]
