# Generated by Django 4.0a1 on 2021-11-26 11:45

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0008_run_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='', max_length=255, verbose_name='Group label')),
                ('dating', models.CharField(blank=True, max_length=255, verbose_name='Dating')),
                ('materials', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None, verbose_name='Materials')),
                ('discovery_place', models.CharField(blank=True, max_length=255, verbose_name='Place of discovery')),
                ('collection', models.CharField(blank=True, max_length=255, verbose_name='Collection')),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255, verbose_name='Label')),
                ('differentiation_information', models.CharField(blank=True, max_length=255, verbose_name='Differentiation information')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='lab.objectgroup')),
            ],
        ),
        migrations.AddField(
            model_name='run',
            name='run_object_groups',
            field=models.ManyToManyField(to='lab.ObjectGroup'),
        ),
    ]
