# Generated by Django 4.0a1 on 2021-12-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0008_run_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='beamline',
            field=models.CharField(choices=[('Microbeam', 'Microbeam')], default='Microbeam', max_length=45, verbose_name='Beamline'),
        ),
    ]
