# Generated by Django 4.0a1 on 2021-12-13 10:18

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0009_alter_run_beamline'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255, verbose_name='Group label')),
                ('inventory', models.CharField(blank=True, max_length=255, verbose_name='Inventory')),
                ('dating', models.CharField(max_length=255, verbose_name='Dating')),
                ('materials', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None, verbose_name='Materials')),
                ('discovery_place', models.CharField(blank=True, max_length=255, verbose_name='Place of discovery')),
                ('collection', models.CharField(blank=True, max_length=255, verbose_name='Collection')),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('differentiation_information', models.CharField(blank=True, max_length=255, verbose_name='Differentiation information')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.objectgroup')),
            ],
        ),
        migrations.AddField(
            model_name='run',
            name='run_object_groups',
            field=models.ManyToManyField(related_name='runs', to='lab.ObjectGroup', verbose_name='Object groups'),
        ),
    ]
