# Generated by Django 4.0a1 on 2021-11-29 10:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0009_objectgroup_object_run_run_object_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='label',
            field=models.CharField(max_length=255, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='objectgroup',
            name='dating',
            field=models.CharField(max_length=255, verbose_name='Dating'),
        ),
        migrations.AlterField(
            model_name='objectgroup',
            name='label',
            field=models.CharField(blank=True, help_text='', max_length=255, verbose_name='Group label'),
        ),
        migrations.AlterField(
            model_name='objectgroup',
            name='materials',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None, verbose_name='Materials'),
        ),
    ]
