# Generated by Django 4.0 on 2022-01-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0010_objectgroup_object_run_run_object_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='toremove',
            field=models.CharField(default='a', max_length=255, verbose_name='TO remove'),
            preserve_default=False,
        ),
    ]
