# Generated by Django 4.0 on 2022-01-12 16:45

from django.db import migrations
import lab.methods.model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0010_objectgroup_object_run_run_object_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='methods',
        ),
        migrations.AddField(
            model_name='run',
            name='detector_ERDA',
            field=lab.methods.model_fields.DetectorCharField('ERDA', '_'),
        ),
        migrations.AddField(
            model_name='run',
            name='detector_FORS_QE65000',
            field=lab.methods.model_fields.DetectorBooleanField('FORS', 'QE65000'),
        ),
        migrations.AddField(
            model_name='run',
            name='detector_FORS_other',
            field=lab.methods.model_fields.DetectorCharField('FORS', '_'),
        ),
        migrations.AddField(
            model_name='run',
            name='detector_HE1',
            field=lab.methods.model_fields.DetectorBooleanField('PIXE', 'HE1'),
        ),
        migrations.AddField(
            model_name='run',
            name='detector_HE2',
            field=lab.methods.model_fields.DetectorBooleanField('PIXE', 'HE2'),
        ),
        migrations.AddField(
            model_name='run',
            name='detector_HE3',
            field=lab.methods.model_fields.DetectorBooleanField('PIXE', 'HE3'),
        ),
        migrations.AddField(
            model_name='run',
            name='detector_HE4',
            field=lab.methods.model_fields.DetectorBooleanField('PIXE', 'HE4'),
        ),
        migrations.AddField(
            model_name='run',
            name='detector_HPGe20',
            field=lab.methods.model_fields.DetectorBooleanField('PIGE', 'HPGe-20'),
        ),
        migrations.AddField(
            model_name='run',
            name='detector_HPGe70',
            field=lab.methods.model_fields.DetectorBooleanField('PIGE', 'HPGe-70'),
        ),
        migrations.AddField(
            model_name='run',
            name='detector_HPGe70N',
            field=lab.methods.model_fields.DetectorBooleanField('PIGE', 'HPGe-70-N'),
        ),
        migrations.AddField(
            model_name='run',
            name='detector_IBIL_QE65000',
            field=lab.methods.model_fields.DetectorBooleanField('IBIL', 'QE65000'),
        ),
        migrations.AddField(
            model_name='run',
            name='detector_IBIL_other',
            field=lab.methods.model_fields.DetectorCharField('IBIL', '_'),
        ),
        migrations.AddField(
            model_name='run',
            name='detector_LE0',
            field=lab.methods.model_fields.DetectorBooleanField('PIXE', 'LE0'),
        ),
        migrations.AddField(
            model_name='run',
            name='detector_NRA',
            field=lab.methods.model_fields.DetectorCharField('NRA', '_'),
        ),
        migrations.AddField(
            model_name='run',
            name='detector_PIPS130',
            field=lab.methods.model_fields.DetectorBooleanField('RBS', 'PIPS - 130°'),
        ),
        migrations.AddField(
            model_name='run',
            name='detector_PIPS150',
            field=lab.methods.model_fields.DetectorBooleanField('RBS', 'PIPS - 150°'),
        ),
        migrations.AddField(
            model_name='run',
            name='filters_for_detector_HE1',
            field=lab.methods.model_fields.FiltersCharField('PIXE', 'HE1', ['100 µm Be', '100 µm Mylar', '200 µm Mylar', '50 µm Al', '100 µm Al', '150 µm Al', '200 µm Al', '13 µm Cr + 50 µm Al', '50 µm Cu', '75 µm Cu', '_']),
        ),
        migrations.AddField(
            model_name='run',
            name='filters_for_detector_HE2',
            field=lab.methods.model_fields.FiltersCharField('PIXE', 'HE2', ['100 µm Be', '100 µm Mylar', '200 µm Mylar', '50 µm Al', '100 µm Al', '150 µm Al', '200 µm Al', '13 µm Cr + 50 µm Al', '50 µm Cu', '75 µm Cu', '_']),
        ),
        migrations.AddField(
            model_name='run',
            name='filters_for_detector_HE3',
            field=lab.methods.model_fields.FiltersCharField('PIXE', 'HE3', ['100 µm Be', '100 µm Mylar', '200 µm Mylar', '50 µm Al', '100 µm Al', '150 µm Al', '200 µm Al', '13 µm Cr + 50 µm Al', '50 µm Cu', '75 µm Cu', '_']),
        ),
        migrations.AddField(
            model_name='run',
            name='filters_for_detector_HE4',
            field=lab.methods.model_fields.FiltersCharField('PIXE', 'HE4', ['100 µm Be', '100 µm Mylar', '200 µm Mylar', '50 µm Al', '100 µm Al', '150 µm Al', '200 µm Al', '13 µm Cr + 50 µm Al', '50 µm Cu', '75 µm Cu', '_']),
        ),
        migrations.AddField(
            model_name='run',
            name='filters_for_detector_LE0',
            field=lab.methods.model_fields.FiltersCharField('PIXE', 'LE0', ['Helium', 'Air']),
        ),
        migrations.AddField(
            model_name='run',
            name='method_ERDA',
            field=lab.methods.model_fields.MethodBooleanField('ERDA'),
        ),
        migrations.AddField(
            model_name='run',
            name='method_FORS',
            field=lab.methods.model_fields.MethodBooleanField('FORS'),
        ),
        migrations.AddField(
            model_name='run',
            name='method_IBIL',
            field=lab.methods.model_fields.MethodBooleanField('IBIL'),
        ),
        migrations.AddField(
            model_name='run',
            name='method_NRA',
            field=lab.methods.model_fields.MethodBooleanField('NRA'),
        ),
        migrations.AddField(
            model_name='run',
            name='method_PIGE',
            field=lab.methods.model_fields.MethodBooleanField('PIGE'),
        ),
        migrations.AddField(
            model_name='run',
            name='method_PIXE',
            field=lab.methods.model_fields.MethodBooleanField('PIXE'),
        ),
        migrations.AddField(
            model_name='run',
            name='method_RBS',
            field=lab.methods.model_fields.MethodBooleanField('RBS'),
        ),
    ]
