# Generated by Django 4.0a1 on 2022-01-17 10:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('euphro_auth', '0009_user_is_lab_admin'),
        ('lab', '0011_run_methods'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beamtimerequest',
            options={'verbose_name': 'Beam time request', 'verbose_name_plural': 'Beam time requests'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(through='lab.Participation', to=settings.AUTH_USER_MODEL, verbose_name='Members'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(1, 'To schedule')], default=1, verbose_name='Status'),
        ),
    ]
