# Generated by Django 4.0a1 on 2022-01-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0012_alter_beamtimerequest_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beamtimerequest',
            name='form_type',
            field=models.CharField(blank=True, choices=[('Sciencescall', 'Sciencescall'), ('IPERION', 'Hyperion'), ('OSCAR', 'Oscar')], max_length=45, verbose_name='Form type'),
        ),
        migrations.AlterField(
            model_name='beamtimerequest',
            name='problem_statement',
            field=models.TextField(blank=True, help_text='Description of the problematic being studied with the beam analysis', max_length=350, verbose_name='Problem statement'),
        ),
    ]
