# Generated by Django 4.0.1 on 2022-01-26 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0013_beamtimerequest_form_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectgroup',
            options={'verbose_name': 'Batch of objects', 'verbose_name_plural': 'Batches of objects'},
        ),
        migrations.AddField(
            model_name='object',
            name='collection',
            field=models.CharField(blank=True, max_length=255, verbose_name='Collection'),
        ),
        migrations.AddField(
            model_name='object',
            name='inventory',
            field=models.CharField(blank=True, max_length=255, verbose_name='Inventory'),
        ),
        migrations.AddField(
            model_name='object',
            name='total_number',
            field=models.IntegerField(blank=True, help_text='Number of objects if more than one', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Total number'),
        ),
    ]
