# Generated by Django 4.0.1 on 2022-02-09 13:16

from django.db import migrations, models

OBJECT_COUNT_ONE_OFF_DEFAULT = 99999


def populate_object_count(apps, _):
    object_group_model = apps.get_model("lab", "ObjectGroup")
    objectgroups = object_group_model.objects.filter(
        object_count=OBJECT_COUNT_ONE_OFF_DEFAULT
    )
    for objectgroup in objectgroups:
        objectgroup.object_count = objectgroup.object_set.count() or 1
        objectgroup.save()


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0014_alter_objectgroup_options_object_collection_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectgroup",
            name="label",
            field=models.CharField(max_length=255, verbose_name="Label"),
        ),
        migrations.AddField(
            model_name="objectgroup",
            name="object_count",
            field=models.PositiveIntegerField(
                default=OBJECT_COUNT_ONE_OFF_DEFAULT, verbose_name="Number of objects"
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="object",
            name="differentiation_information",
        ),
        migrations.RemoveField(
            model_name="object",
            name="total_number",
        ),
        migrations.RunPython(
            code=populate_object_count,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="objectgroup",
            name="inventory",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Inventory number"
            ),
        ),
        migrations.AlterField(
            model_name="objectgroup",
            name="label",
            field=models.CharField(blank=True, max_length=255, verbose_name="Label"),
        ),
        migrations.AlterField(
            model_name="objectgroup",
            name="label",
            field=models.CharField(max_length=255, verbose_name="Label"),
        ),
    ]
