# Generated by Django 4.0.1 on 2022-02-14 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0015_objectgroup_object_count_alter_objectgroup_inventory_and_more_squashed_0016_alter_objectgroup_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectgroup',
            options={'verbose_name': 'Object / Sample', 'verbose_name_plural': 'Object(s) / Sample(s'},
        ),
    ]
