# Generated by Django 4.0.1 on 2022-02-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0015_alter_project_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="new_status",
            field=models.IntegerField(
                choices=[
                    (1, "Created"),
                    (11, "Ask for execution"),
                    (21, "Ongoing"),
                    (31, "Finished"),
                ],
                default=1,
                verbose_name="Run status",
            ),
        ),
    ]
