# Generated by Django 4.0.1 on 2022-02-21 18:33

from django.db import migrations

RUN_STATUS_MAPPING = {
    "New": 1,
    "Ask for execution": 11,
    "Planned": 11,
    "Started": 21,
    "Finished": 31,
}
REVERSE_RUN_STATUS_MAPPING = {
    1: "New",
    11: "Ask for execution",
    21: "Planned",
    31: "Finished",
}


def update_run_status(apps, _):
    run_model = apps.get_model("lab", "Run")
    for old, new in RUN_STATUS_MAPPING.items():
        run_model.objects.filter(status=old).update(new_status=new)


def rewind_update_run_status(apps, _):
    run_model = apps.get_model("lab", "Run")
    for new, old in REVERSE_RUN_STATUS_MAPPING.items():
        run_model.objects.filter(new_status=new).update(status=old)


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0016_run_new_status"),
    ]

    operations = [migrations.RunPython(update_run_status, rewind_update_run_status)]
