# Generated by Django 4.0.1 on 2022-03-03 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0015_alter_project_status'),
        ('lab', '0016_alter_objectgroup_options'),
    ]

    operations = [
    ]
