# Generated by Django 4.0.1 on 2022-02-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0017_change_run_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="run",
            name="status",
        ),
    ]
