# Generated by Django 4.0.1 on 2022-03-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0017_merge_20220303_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='label',
            field=models.CharField(max_length=255, verbose_name='Run label'),
        ),
        migrations.AddConstraint(
            model_name='run',
            constraint=models.UniqueConstraint(fields=('label', 'project'), name='label_project_unique'),
        ),
    ]
