# Generated by Django 4.0.1 on 2022-02-21 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0018_remove_run_new_status_alter_run_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='run',
            old_name='new_status',
            new_name='status',
        ),
    ]
