# Generated by Django 4.0.1 on 2022-03-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0018_alter_run_label_run_label_project_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='run',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start date'),
        ),
    ]
