# Generated by Django 4.0.1 on 2022-03-19 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0016_run_new_status_squashed_0019_rename_new_status_run_status'),
        ('lab', '0019_alter_run_end_date_alter_run_start_date'),
    ]

    operations = [
    ]
