# Generated by Django 4.0.1 on 2022-03-19 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0020_merge_20220319_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
    ]
