# Generated by Django 4.0.1 on 2022-03-28 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0021_remove_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='lab.project', verbose_name='Project'),
        ),
    ]
