# Generated by Django 4.0.5 on 2022-07-18 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0023_alter_project_name_alter_run_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^[\\w\\- ]+$', message='Only alphanumeric, underscore, hyphen and space characters are allowed')], verbose_name='Project name'),
        ),
        migrations.AlterField(
            model_name='run',
            name='label',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[\\w\\- ]+$', message='Only alphanumeric, underscore, hyphen and space characters are allowed')], verbose_name='Run label'),
        ),
    ]
