# Generated by Django 4.2.1 on 2023-05-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lab", "0026_project_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="objectgroup",
            name="c2rmf_id",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="C2RMF ID"
            ),
        ),
    ]
