# Generated by Django 4.2.1 on 2023-05-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lab", "0027_objectgroup_c2rmf_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectgroup",
            name="dating",
            field=models.CharField(blank=True, max_length=255, verbose_name="Dating"),
        ),
    ]
