# Generated by Django 4.2.6 on 2023-11-07 14:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("lab", "0029_project_is_data_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="objectgroup",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Date this entry was first created",
                verbose_name="Created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="objectgroup",
            name="modified",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Date this entry was most recently changed.",
                verbose_name="Modified",
            ),
        ),
    ]
