# Generated by Django 4.2.6 on 2023-11-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lab", "0030_objectgroup_created_objectgroup_modified"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="confidential",
            field=models.BooleanField(
                default=False,
                help_text="Mark this project as confidential. This will hide it from external servicecs (Euphrosyne Diglab, ...).",
                verbose_name="Confidential",
            ),
        ),
    ]
