# Generated by Django 5.0.3 on 2024-04-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0032_alter_participation_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="ror_id",
            field=models.CharField(
                blank=True,
                help_text="Research Organization Registry ID",
                max_length=255,
                null=True,
                verbose_name="ROR ID",
            ),
        ),
    ]
