# Generated by Django 5.0.3 on 2024-04-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0033_institution_ror_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="country",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="country"
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="name",
            field=models.CharField(max_length=255, verbose_name="name"),
        ),
    ]
