# Generated by Django 5.0.3 on 2024-04-03 18:56

import django.db.models.deletion
from django.db import migrations, models


def move_discovery_place_to_location_label(apps, _):
    objectgroup_model = apps.get_model("lab", "ObjectGroup")
    location_model = apps.get_model("lab", "Location")
    for og in objectgroup_model.objects.all():
        if og.discovery_place:
            location, _ = location_model.objects.get_or_create(label=og.discovery_place)
            og.discovery_place_location = location
            og.save()


def move_location_label_to_discovery_place(apps, _):
    objectgroup_model = apps.get_model("lab", "ObjectGroup")
    for og in objectgroup_model.objects.all():
        if og.discovery_place_location:
            og.discovery_place = og.discovery_place_location.label
            og.save()


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0034_alter_institution_country_alter_institution_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="Latitude"),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="Longitude"),
                ),
                (
                    "geonames_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Geonames ID"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(fields=("label",), name="unique_label"),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                fields=("latitude", "longitude"), name="unique_lat_long"
            ),
        ),
        migrations.AddField(
            model_name="objectgroup",
            name="discovery_place_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="lab.location",
                verbose_name="Place of discovery",
            ),
        ),
        migrations.RunPython(
            move_discovery_place_to_location_label,
            move_location_label_to_discovery_place,
        ),
        migrations.RemoveField(
            model_name="objectgroup",
            name="discovery_place",
        ),
    ]
