# Generated by Django 5.0.3 on 2024-04-05 16:02

import django.db.models.deletion
from django.db import migrations, models


def move_dating_to_period_label(apps, _):
    objectgroup_model = apps.get_model("lab", "ObjectGroup")
    period_model = apps.get_model("lab", "Period")
    for og in objectgroup_model.objects.all():
        if og.old_dating:
            period, _ = period_model.objects.get_or_create(
                label=og.old_dating, theso_joconde_id=None
            )
            og.dating = period
            og.save()


def move_period_label_to_dating(apps, _):
    objectgroup_model = apps.get_model("lab", "ObjectGroup")
    for og in objectgroup_model.objects.all():
        if og.dating:
            og.old_dating = og.dating.label
            og.save()


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0035_location_remove_objectgroup_discovery_place_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Period",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "theso_joconde_id",
                    models.CharField(
                        blank=True,
                        null=True,
                        max_length=255,
                        verbose_name="Joconde Thesorus ID",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="period",
            constraint=models.UniqueConstraint(
                fields=("label",), name="period_unique_label"
            ),
        ),
        migrations.AddConstraint(
            model_name="period",
            constraint=models.UniqueConstraint(
                fields=("theso_joconde_id",), name="period_unique_theso_joconde_id"
            ),
        ),
        migrations.RenameField(
            model_name="objectgroup",
            old_name="dating",
            new_name="old_dating",
        ),
        migrations.AddField(
            model_name="objectgroup",
            name="dating",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="lab.period",
                verbose_name="Dating",
            ),
        ),
        migrations.RunPython(
            move_dating_to_period_label,
            move_period_label_to_dating,
        ),
        migrations.RemoveField(
            model_name="objectgroup",
            name="old_dating",
        ),
    ]
