# Generated by Django 5.0.4 on 2024-05-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0036_period_period_period_unique_label_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="participation",
            name="on_premises",
            field=models.BooleanField(
                default=False,
                help_text="Is the user going to be at the New AGLAE facility?",
                verbose_name="On premises",
            ),
        ),
    ]
