# Generated by Django 5.0.4 on 2024-05-17 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0036_period_period_period_unique_label_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="period",
            name="period_unique_label",
        ),
        migrations.AlterField(
            model_name="objectgroup",
            name="dating",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lab.period",
                verbose_name="Dating",
            ),
        ),
        migrations.AlterField(
            model_name="objectgroup",
            name="discovery_place_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lab.location",
                verbose_name="Place of discovery",
            ),
        ),
        migrations.AddConstraint(
            model_name="period",
            constraint=models.UniqueConstraint(
                fields=("label", "theso_joconde_id"),
                name="period_unique_label_theso_joconde_id",
            ),
        ),
    ]
