# Generated by Django 5.0.7 on 2024-09-20 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0039_era_remove_period_period_unique_theso_joconde_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeasuringPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("comments", models.TextField(blank=True, verbose_name="Comments")),
                (
                    "object_group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="measuring_points",
                        to="lab.objectgroup",
                        verbose_name="Object group",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measuring_points",
                        to="lab.run",
                        verbose_name="Run",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="measuringpoint",
            constraint=models.UniqueConstraint(
                fields=("name", "run"), name="unique_name_per_run"
            ),
        ),
    ]
