# Generated by Django 5.1.1 on 2024-10-24 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0038_location_unique_geonames_id"),
        ("lab", "0039_era_remove_period_period_unique_theso_joconde_id_and_more"),
    ]

    operations = []
