# Generated by Django 5.0.7 on 2024-10-01 09:03

import django.db.models.deletion
from django.db import migrations, models


def move_run_object_groups_to_new_model(apps, _):
    old_model = apps.get_model("lab", "Run_run_object_groups")
    new_model = apps.get_model("lab", "RunObjectGroup")

    relations = old_model.objects.values_list("run_id", "objectgroup_id")

    for run_id, object_group_id in relations:
        new_model.objects.create(run_id=run_id, objectgroup_id=object_group_id)

    old_model.objects.all().delete()


def reverse_move_run_object_groups_to_new_model(apps, _):
    old_model = apps.get_model("lab", "Run_run_object_groups")
    new_model = apps.get_model("lab", "RunObjectGroup")

    relations = new_model.objects.values_list("run_id", "objectgroup_id")

    for run_id, object_group_id in relations:
        old_model.objects.create(run_id=run_id, objectgroup_id=object_group_id)

    new_model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0040_measuringpoint_created_measuringpoint_modified"),
    ]

    operations = [
        migrations.CreateModel(
            name="RunObjectGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date this entry was first created",
                        verbose_name="Created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date this entry was most recently changed.",
                        verbose_name="Modified",
                    ),
                ),
                (
                    "objectgroup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lab.objectgroup",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lab.run"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(
            move_run_object_groups_to_new_model,
            reverse_code=reverse_move_run_object_groups_to_new_model,
        ),
        migrations.RemoveField(
            model_name="run",
            name="run_object_groups",
        ),
        migrations.AddField(
            model_name="run",
            name="run_object_groups",
            field=models.ManyToManyField(
                related_name="runs",
                through="lab.RunObjectGroup",
                to="lab.objectgroup",
                verbose_name="Object groups",
            ),
        ),
    ]
