# Generated by Django 5.1.1 on 2024-10-09 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0042_runobjetgroupimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasuringPointImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date this entry was first created', verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date this entry was most recently changed.', verbose_name='Modified')),
                ('point_location', models.JSONField(null=True, verbose_name='Point location of image')),
                ('measuring_point', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='lab.measuringpoint')),
                ('run_object_group_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measuring_point_images', to='lab.runobjetgroupimage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
