# Generated by Django 5.1.1 on 2024-10-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0043_measuringpointimage'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='runobjetgroupimage',
            constraint=models.UniqueConstraint(fields=('path', 'transform', 'run_object_group'), name='run_object_group_image_unique_path_transform_perrun_object_group'),
        ),
    ]
