# Generated by Django 5.1.5 on 2025-02-11 13:59

from django.db import migrations


def apply_migration(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.get_or_create(name="vm admin")


def revert_migration(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.get(
        name="vm admin",
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        (
            "lab",
            "0045_objectgroupthumbnail",
        ),
    ]

    operations = [
        migrations.RunPython(
            apply_migration,
            revert_migration,
        ),
    ]
