# Generated by Django 5.1.5 on 2025-03-06 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0046_auto_20250211_1459"),
    ]

    operations = [
        migrations.AddField(
            model_name="objectgroup",
            name="is_differentiated",
            field=models.BooleanField(
                default=False, verbose_name="Is differentiated object?"
            ),
        ),
        migrations.AddField(
            model_name="objectgroup",
            name="parent_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="differentiated_objects",
                to="lab.objectgroup",
                verbose_name="Parent Object Group",
            ),
        ),
        migrations.DeleteModel(
            name="Object",
        ),
    ]
