# Generated by Django 5.1.5 on 2025-03-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0046_auto_20250211_1459"),
    ]

    operations = [
        migrations.AddField(
            model_name="participation",
            name="on_premises",
            field=models.BooleanField(
                default=False,
                help_text="Is the user going to be at the New AGLAE facility?",
                verbose_name="On premises",
            ),
        ),
    ]
