# Generated by Django 5.2.1 on 2025-06-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0046_auto_20250211_1459"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="comments",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
    ]
