# Generated by Django 5.1.5 on 2025-03-20 16:03

from django.db import migrations, models


def set_leader_on_premises(apps, _):
    participation_model = apps.get_model("lab", "Participation")

    participation_model.objects.filter(is_leader=True, on_premises=False).update(
        on_premises=True
    )


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0047_alter_project_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="participation",
            name="on_premises",
            field=models.BooleanField(
                default=False,
                help_text="Is the user going to be at the New AGLAE facility?",
                verbose_name="On premises",
            ),
        ),
        migrations.RunPython(
            set_leader_on_premises, reverse_code=migrations.RunPython.noop
        ),
    ]
