# Generated by Django 5.2.5 on 2025-10-09 08:28

import django.db.models.deletion
from django.db import migrations, models


def migrate_c2rmf_id_to_external_reference(apps, schema_editor):
    ObjectGroup = apps.get_model("lab", "ObjectGroup")
    ExternalObjectReference = apps.get_model("lab", "ExternalObjectReference")

    for obj_group in ObjectGroup.objects.exclude(c2rmf_id__isnull=True).exclude(
        c2rmf_id=""
    ):
        ExternalObjectReference.objects.create(
            object_group=obj_group,
            provider_name="eros",
            provider_object_id=obj_group.c2rmf_id,
        )


def reverse_migrate_c2rmf_id_to_external_reference(apps, schema_editor):
    ExternalObjectReference = apps.get_model("lab", "ExternalObjectReference")

    for ext_ref in ExternalObjectReference.objects.filter(provider_name="eros"):
        obj_group = ext_ref.object_group
        obj_group.c2rmf_id = ext_ref.provider_object_id
        obj_group.save()
        ext_ref.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0048_participation_on_premises"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalObjectReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date this entry was first created",
                        verbose_name="Created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date this entry was most recently changed.",
                        verbose_name="Modified",
                    ),
                ),
                (
                    "provider_name",
                    models.CharField(
                        help_text="Provider identifier (e.g., 'eros', 'pop')",
                        max_length=50,
                        verbose_name="Provider Name",
                    ),
                ),
                (
                    "provider_object_id",
                    models.CharField(
                        help_text="Unique identifier in the provider's system",
                        max_length=255,
                        verbose_name="Provider Object ID",
                    ),
                ),
                (
                    "object_group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_reference",
                        to="lab.objectgroup",
                        verbose_name="Object Group",
                    ),
                ),
            ],
            options={
                "verbose_name": "External Object Reference",
                "verbose_name_plural": "External Object References",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider_name", "provider_object_id"),
                        name="unique_provider_object",
                    )
                ],
            },
        ),
        migrations.RunPython(
            code=migrate_c2rmf_id_to_external_reference,
            reverse_code=reverse_migrate_c2rmf_id_to_external_reference,
        ),
        migrations.RemoveField(
            model_name="objectgroup",
            name="c2rmf_id",
        ),
        migrations.CreateModel(
            name="AnnotatedObjectGroup",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("lab.objectgroup",),
        ),
    ]
