# Generated by Django 5.2.5 on 2025-10-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0050_employer_participation_employer"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="institution",
            name="unique_name_country_per_institution",
        ),
        migrations.AddConstraint(
            model_name="institution",
            constraint=models.UniqueConstraint(
                fields=("name", "country", "ror_id"),
                name="unique_name_country_rorid_per_institution",
            ),
        ),
    ]
