# Generated by Django 5.2.5 on 2025-10-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0051_remove_institution_unique_name_country_per_institution_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employer",
            name="function",
            field=models.CharField(
                default="function", max_length=150, verbose_name="function"
            ),
            preserve_default=False,
        ),
    ]
