# Generated by Django 5.2.9 on 2026-01-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0052_alter_employer_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='on_premises',
            field=models.BooleanField(default=False, help_text='Is the user going to be at the facility?', verbose_name='On premises'),
        ),
    ]
