# Generated by Django 4.0a1 on 2021-09-24 12:02
# Modified on 2021-10-06 to remove any content.
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("euphro_auth", "0001_initial"),
    ]

