# Generated by Django 4.0a1 on 2021-09-24 12:02
import pathlib

from django.db import migrations
from django.core.management import call_command


def load_fixture(_, __):
    fixture_filename = (pathlib.Path(__file__)).with_suffix(".yaml").name
    call_command("loaddata", fixture_filename, format="yaml", app="euphro_auth")


class Migration(migrations.Migration):

    dependencies = [
        ("euphro_auth", "0001_initial"),
    ]

    operations = [migrations.RunPython(load_fixture, lambda *x: None)]
