# Generated by Django 4.0a1 on 2021-09-30 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('euphro_auth', '0002_load_group_fixture'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date this entry was first created', verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date this entry was most recently changed.', verbose_name='Modified')),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='euphro_auth.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
