# Generated by Django 4.0a1 on 2021-10-06 11:38

from django.db import migrations
from django.db.models import Q


def delete_extra_groups(apps, _):
    group_model = apps.get_model("auth", "Group")
    group_model.objects.filter(
        Q(name="Project member") | Q(name="Project leader")
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("euphro_auth", "0004_remove_userinvitation_completed_and_more"),
    ]

    operations = [migrations.RunPython(delete_extra_groups, lambda *x: None)]
