# Generated by Django 4.0a1 on 2021-10-11 19:47

from django.db import migrations


def add_non_admin_users_to_participant_group(apps, _):
    group_model = apps.get_model("auth", "Group")
    for participant_group_id in group_model.objects.filter(
        name="Project Participant"
    ).values_list("id", flat=True):
        user_model = apps.get_model("euphro_auth", "User")
        for user in user_model.objects.filter(groups=None):
            user.groups.add(participant_group_id)


def remove_users_from_participant_group(apps, _):
    group_model = apps.get_model("auth", "Group")
    for participant_group_id in group_model.objects.filter(
        name="Project Participant"
    ).values_list("id", flat=True):
        user_model = apps.get_model("euphro_auth", "User")
        for user in user_model.objects.filter(groups=participant_group_id):
            user.groups.remove(participant_group_id)


class Migration(migrations.Migration):

    dependencies = [
        ("euphro_auth", "0005_delete_extra_groups"),
    ]

    operations = [
        migrations.RunPython(
            add_non_admin_users_to_participant_group,
            remove_users_from_participant_group,
        )
    ]
