# Generated by Django 4.0a1 on 2021-10-12 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('euphro_auth', '0006_default_to_participant_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInvitation',
        ),
        migrations.CreateModel(
            name='UserInvitation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('euphro_auth.user',),
        ),
    ]
