# Generated by Django 4.0.1 on 2022-01-26 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('euphro_auth', '0009_user_is_lab_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinvitation',
            options={'verbose_name': 'User invitation', 'verbose_name_plural': 'User invitations'},
        ),
    ]
