# Generated by Django 5.1.3 on 2025-01-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("euphro_auth", "0010_alter_userinvitation_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cgu_accepted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="CGU accepted at"
            ),
        ),
    ]
