# Generated by Django 5.1.5 on 2025-03-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("euphro_auth", "0011_user_cgu_accepted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferred_language",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="preferred language"
            ),
        ),
    ]
