# Generated by Django 5.0.6 on 2024-07-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lab", "0039_era_remove_period_period_unique_theso_joconde_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_viewed",
                    models.BooleanField(
                        default=False,
                        help_text="Has been viewed by an admin",
                        verbose_name="Viewed",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Sent at"),
                ),
                (
                    "user_email",
                    models.EmailField(max_length=254, verbose_name="User emaio"),
                ),
                ("user_first_name", models.CharField(max_length=150)),
                ("user_last_name", models.CharField(max_length=150)),
                ("user_institution", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "runs",
                    models.ManyToManyField(related_name="data_requests", to="lab.run"),
                ),
            ],
            options={
                "verbose_name": "Data Request",
                "verbose_name_plural": "Data Requests",
            },
        ),
    ]
