# Generated by Django 5.0.7 on 2024-07-19 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "data_request",
            "0002_alter_datarequest_options_alter_datarequest_created_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DataAccessEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255, verbose_name="Path")),
                (
                    "access_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Access time"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modified"),
                ),
                (
                    "data_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_access_events",
                        to="data_request.datarequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "data access event",
                "verbose_name_plural": "data access events",
            },
        ),
    ]
